### ISSUE TITLE
serviceType_lightBulb' was not declared in this scope

### ISSUE THREAD

**Issue by eriksmets** [etwmc/Personal-HomeKit-HAP#44]
`Accessory.cpp:error: 'serviceType_lightBulb' was not declared in this scope`

PHKAccessory.h:, line 90-109:
 replacing 'charType_' with 'serviceType_' fixes this.

(also in PHKAccessory.cpp on line 576.)

**Comment by eriksmets** [comment]
i've submitted a pull request which fixes this.

**Comment by etwmc** [comment]
it's fixed in the last commit, alongside with the new service types. 
Sorry for the inconvenience, I haven't fix my Github email problem yet.
