### ISSUE TITLE
Error G++

### ISSUE THREAD

**Issue by dimlam** [etwmc/Personal-HomeKit-HAP#46]
Hi, 

Is there someone how can help me to solve this issue ?
I'm trying to install al this on a RPi
But when I do a "make", this is the error I get :

root@mainpi:~/Personal-HomeKit-HAP-master# make
g++ -Os -s -w -c main.cpp
In file included from main.cpp:11:0:
PHKNetworkIP.h:82:27: error: ISO C++ forbids initialization of member ‘index’ [-fpermissive]
PHKNetworkIP.h:82:27: error: making ‘index’ static [-fpermissive]
PHKNetworkIP.h:82:27: error: ISO C++ forbids in-class initialization of non-const static member ‘index’
PHKNetworkIP.h:83:18: error: ISO C++ forbids initialization of member ‘data’ [-fpermissive]
PHKNetworkIP.h:83:18: error: making ‘data’ static [-fpermissive]
PHKNetworkIP.h:83:18: error: invalid in-class initialization of static data member of non-integral type 

Thanks for the help

**Comment by beckmx** [comment]
I get that too

error: ISO C++ forbids initialization of member 'index' [-fpermissive]

**Comment by beckmx** [comment]
Okay I think I solved the problem in here, you have to install clang and change the compiler in the makefile, it says g++ you need to change it to c++ AFTER you installed clang
