### ISSUE TITLE
byteswap.h and OSX

### ISSUE THREAD

**Issue by rawmean** [etwmc/Personal-HomeKit-HAP#50]
byteswap.h is not portable and is not included in OSX so the code does not compile on OS X anymore.

**Comment by yannickulrich** [comment]
Change the include line to the following:
```
#if defined(__APPLE__)
#include <libkern/OSByteOrder.h>
#define bswap_16 OSSwapInt16
#define bswap_32 OSSwapInt32
#define bswap_64 OSSwapInt64
#else
#include <byteswap.h>
#endif
```
worked for me on Yosemite

**Comment by etwmc** [comment]
byteswap.h has been removed from the new commit, so I would temporary close it until it occurs again
