### ISSUE TITLE
statusCode is uninitialized in handleAccessory in PHKAccessory.cpp

### ISSUE THREAD

**Issue by steveb48** [etwmc/Personal-HomeKit-HAP#55]
Hi,
I've gotten much farther with your new drop. I had a problem with statusCode being used in the while loop in handleAccessory before it was initialized. I just changed the declaration to 
    int statusCode = 0;

and now I'm getting events processed. 
Thanks,
Steve

**Comment by etwmc** [comment]
Duly noted, and the code has been updated. 
What kind of compiler did you use? Because I thought int init to 0 is a part of C99
Thanks

**Comment by steveb48** [comment]
MacBook Pro. This was keeping me from going through the loop once. All running now.
thanks
Steve
