### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by todely** [etwmc/Personal-HomeKit-HAP#56]
Hello,

I get an error at make.
When it come to PHKAccessory.cpp compil error:
PHKAccessory.cpp: In function 'void updateValueFromDeviceEnd(characteristics*, int, int, std::string)':
PHKAccessory.cpp:336:114: error: cannot pass objects of non-trivially-copyable type 'std::string {aka class std::basic_string<char>}' through '...'
     snprintf(broadcastTemp, 1024, "{\"characteristics\":[{\"aid\":%d,\"iid\":%d,\"value\":%s}]}", aid, iid, value);
                                                                                                                  ^
makefile:42: recipe for target 'PHKAccessory.o' failed
make: *** [PHKAccessory.o] Error 1

What's wrong ?
Thanks

**Comment by etwmc** [comment]
What platform and compiler version are you using?

**Comment by todely** [comment]
Raspberry on raspbian

**Comment by etwmc** [comment]
Clang version?

**Comment by todely** [comment]
How to check on raspberry ?

**Comment by etwmc** [comment]
clang -v ?

**Comment by todely** [comment]
Clang does not exist....
-bash: clang : commande introuvable

Need to install it ?

**Comment by etwmc** [comment]
How about gcc? 
You can check with gcc -version

**Comment by todely** [comment]
- $ clang -v
Debian clang version 3.0-6.2 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: arm-unknown-linux-gnueabihf
Thread model: posix

**Comment by todely** [comment]
$ gcc --version
gcc (Raspbian 4.8.2-21~rpi3rpi1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by beckmx** [comment]
Hello @etwmc I redownloaded the code and found the same issue, I tested with gcc gcc version 4.7.2 20121015 (Red Hat 4.7.2-5) (GCC) and clang version 3.4.2 both are poping the error, is it safe If I make a rollback? and use the previous version?

**Comment by beckmx** [comment]
the problem is with the sprintf method, so I just commented, and the compiler continued

**Comment by etwmc** [comment]
Can you guys try the new push? 
My Linux box haven't have gcc 4.8 for a while now

**Comment by beckmx** [comment]
it says PHKAccessory.cpp:609:1: error: stray '\357' in program

**Comment by beckmx** [comment]
yes it compiles now fine, my previous error was a strange char I added, thanx ;)

**Comment by todely** [comment]
Works too
Thanks !
