### ISSUE TITLE
_ZNSt8ios_baseC2Ev

### ISSUE THREAD

**Issue by beckmx** [etwmc/Personal-HomeKit-HAP#58]
Hello @etwmc today I encounter this issue on another platform, any idea what could this mean?

./PHK: can't resolve symbol '_ZNSt8ios_baseC2Ev' in lib './PHK'.

Do you think with the -static flag the application can run fine?

Greetings!

**Comment by etwmc** [comment]
Tried "make clean" yet? 
Otherwise, what platform and OS are you using?

**Comment by beckmx** [comment]
Yes I did clean, I am using openwrt but I am guessing the libraries inside
the board are not exactly the same as the compilation, is there any flag to
bundle everything in a single file? Without dynamic linking?

**Comment by etwmc** [comment]
The program itself doesn't rely on dynamic linking (I don't think any program rely on that, static and dynamic should work the same)
For how to compile static, I think that's your compiler's setting. Just add the header in the makefile and it should work fine.
