### ISSUE TITLE
how to launch python script when turn on accessory ?

### ISSUE THREAD

**Issue by todely** [etwmc/Personal-HomeKit-HAP#59]
How can i add python-shell command when i turn on or off an accessory ?
(purpuse is to turn on / off some GPIO)

Does Wemo device can be add as accessory ?

Thanks !

**Comment by etwmc** [comment]
If you can run python from a C code (I usually go with separate process with Unix Socket, but I've heard you can call python directly from C, so you can change the code in accessory implementation to do it? ) But GPIO is usually has some API to do so, or exposed to the system in some form of files/socket from kernel. 
Wemo is possible as long as you can figure out a way to control it under C/C++, or has a small process to do the control with some message passing. 
(Sorry to replying this late, I stop to pin GitHub in Safari after switching Developer Preview, and I still have no idea why I have no email from GitHub)
