### ISSUE TITLE
License

### ISSUE THREAD

**Issue by colemancda** [etwmc/Personal-HomeKit-HAP#61]
Under what License do you provide this code?

**Comment by etwmc** [comment]
As is, do whatever you want for it, so basically BSD? 
(The crypto part is directly copy from other repo in git, so they might have a different one)

**Comment by yene** [comment]
Please add a LICENSE file. Thanks

**Comment by etwmc** [comment]
I got MIT License in the file. 
But again, just as is, contribute if you find something weird or bugs (or just report, but I'm kinda busy these days), and promote this and open source if you can. 
Thank you

**Comment by yene** [comment]
Thank you
